name: Update GitHub Stats

on:
  push:
    branches:
      - main

  schedule:
    - cron: "17 4 1 * *"

  workflow_dispatch:

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_STATS_TOKEN }}
  GH_USERNAME: ViridianAStar

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate stats
        run: |
          mkdir -p assets
          python .github/generatestats.py

      - name: Commit stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/github-stats.svg

          if git diff --cached --quiet; then
            echo "No changes."
          else
            git commit -m "chore: update GitHub stats"
            git push
          fi
